name: valuutamuunnin
description: An absolute bare-bones web app.
version: 2.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
#  path: ^1.7.0
  intl: ^0.16.1

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.12.0-dev.1
  pedantic: ^1.9.0
